input_dir = 'app/assets/javascripts'

coffeescript_options = {
  input: input_dir,
  output: 'app/assets/javascripts',
  patterns: [%r{^#{input_dir}/(.+\.(?:coffee|coffee\.md|litcoffee))$}]
}

guard 'coffeescript', coffeescript_options do
  coffeescript_options[:patterns].each { |pattern| watch(pattern) }
end
